### ISSUE TITLE
Please add option enable/disable showing other Interfaces

### ISSUE THREAD

**Issue by varlesh** [kotelnik/plasma-applet-network-monitor#1]
It will be very convenient, because it uses WiFi AP.
![snapshot1](https://cloud.githubusercontent.com/assets/8083855/7484939/93c4782c-f397-11e4-96a7-47e4222cfc1c.png)

**Comment by kotelnik** [comment]
That's on my TODO list for this plasmoid. I'll try to add a white-list functionality this week.

**Comment by varlesh** [comment]
Thx )) Good luck!

**Comment by kotelnik** [comment]
OK, I've made white-list and black-list filter possibility. Is it working for you? I somehow tested it but you know... :)

**Comment by varlesh** [comment]
Thx) This working fine!
