### ISSUE TITLE
lo always shows, doesn't respect white/blacklists

### ISSUE THREAD

**Issue by fatino** [kotelnik/plasma-applet-network-monitor#2]
![network-monitor](https://cloud.githubusercontent.com/assets/408612/7551969/9c03846c-f69c-11e4-806f-020b7d57289a.png)

I'm on r133.dfbbb78 compiled from AUR on arch of course.

**Comment by kotelnik** [comment]
That's right. Because lo is an exception and you can hide/show it in "General" settings with "Show loopback" checkbox. But I should at least move that checkbox to "Filter" settings. I'll do that in next release.
