### ISSUE TITLE
Useless unless using network manager?

### ISSUE THREAD

**Issue by Soukyuu** [kotelnik/plasma-applet-network-monitor#6]
I'm managing my network (fixed IP LAN) via netctl. I've installed this applet using the [AUR package](https://aur.archlinux.org/packages/plasma5-applets-network-monitor-git/) and all it ever shows me is the loopback interface. Disabling that, it shows me a red network icon and that's all. My connection works just fine though, so it seems it's not detecting it.

Is this applet useless when not using network manager to handle the connections?

**Comment by kotelnik** [comment]
Hi! Yes, for now. The widget is using native KDE plasmaNM datasource which depends on running network manager. But I'll investigate other options and get back to you.

**Comment by Soukyuu** [comment]
Thanks for the response, will be waiting for any news then, as it seems to be the only widget that works decently on a vertical taskbar, as well.

**Comment by kotelnik** [comment]
After a little investigation I think I might be able to make it work without NetworkManager. Although for now it will probably not recognize disconnected devices and just show them all (based on set filter of course). I'm starting to work on it right now... And in time I'll try to resolve the connected/disconnected problem, too.

**Comment by kotelnik** [comment]
Please try the my latest commit / AUR package. It should now work without NM along with showing connected-only devices.

**Comment by Soukyuu** [comment]
Sorry for the late reply - it works just fine now, many thanks!

**Comment by kotelnik** [comment]
Glad to hear that :)
